version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Build
          command: ./gradlew assembleCloudlessDebug

general:
  branches:
    only:
     - development # list of branches to build
